- docs/content/docs/1.getting-started/2.installation.md
- Fixed the `wrangler` installation section snippets for `npm` & `bun`
> Fixed `wrangler` installation snippets for `npm` & `bun`

- docs/content/docs/1.getting-started/3.deploy.md
Sorry, I missed the env in the warning message. Original PR https://github.com/nuxt-hub/core/pull/6.
> Fixed env instructions in warning message

- docs/content/docs/1.getting-started/3.deploy.md
Fixing a typo: bingins -> bindings
> docs: Fix typo in 3.deploy.md

- docs/content/docs/2.storage/3.blob.md
- Remove unused variable
- Fix file type
> docs: Fix code snippet in 3.blob.md

- playground/server/api/kv/[key].delete.ts
- playground/server/api/kv/index.put.ts
- src/server/utils/blob.ts
- src/server/utils/database.ts
- src/server/utils/hooks.ts
- src/server/utils/kv.ts
> docs(storage): adds JSDocs

- docs/content/docs/1.getting-started/2.installation.md
- docs/content/docs/1.getting-started/3.deploy.md
- docs/content/docs/1.getting-started/4.remote-storage.md
- package.json
- pnpm-lock.yaml
- src/module/index.ts
> feat: support remote storage per env

- docs/package.json
- package.json
- playground/package.json
- pnpm-lock.yaml
- src/module/index.ts
- src/module/runtime/server/api/_hub/blob/index.post.ts
- src/module/runtime/server/middleware/1.hub-auth.ts
https://github.com/nuxt-hub/core/assets/904724/cf25cc3c-988d-4f67-b71b-bf088ec967ac
> feat: add support for Blob & KV in devtools

- docs/content/docs/1.getting-started/2.installation.md
resolved #62 .
Add a Use Nuxi(Nuxt CLI) section to the Install documentation.
> docs: add section on installation using `nuxi module add`

- docs/content/docs/1.getting-started/3.deploy.md
> docs: added clarifications in self-hosted deployments

- pnpm-lock.yaml
- src/runtime/server/api/_hub/cache/[...key].delete.ts
- src/runtime/server/api/_hub/cache/[...key].get.ts
- src/runtime/server/api/_hub/cache/index.get.ts
- src/runtime/server/utils/cache.ts
> feat: cache management

- src/utils.ts
> feat: add server cache tab to devtools

- docs/content/docs/1.getting-started/4.remote-storage.md
Fixes a broken internal link 🤠
> docs: Fix broken link in remote section

- playground/server/api/blob/index.put.ts
- pnpm-lock.yaml
- src/runtime/server/api/_hub/blob/index.post.ts
- src/runtime/server/utils/blob.ts
> fix: don't add random suffix by default

- src/utils.ts
This PR corrects a typo in variable name. From `wranger` to `wrangler` ;)
> chore: fix wrangler typo in utils

- docs/content/docs/4.recipes/2.drizzle.md
Solves #105
More info: https://orm.drizzle.team/kit-docs/upgrade-21#how-to-migrate-to-0210
> docs: update drizzle instructions

- package.json
Hello 👋,
This PR add the script `lint:fix` to be able to use the eslint linter since you enable stylistic in the flat config.
> chore: add lint fix script

- src/module.ts
> fix: build

- src/features.ts
- src/module.ts
- src/utils/build.ts
- src/utils/devtools.ts
> fix(module): invalid resolved path in npm package

- .github/workflows/autofix.yml
- .gitignore
- package.json
> chore(ci): Add pkg.pr.new for package preview on pull requests

- docs/content/1.docs/4.recipes/2.drizzle.md
- Fixed a typo in the server tasks path
> docs: improve drizzle seed example

- src/runtime/cache/server/api/_hub/cache/[...key].get.ts
- src/runtime/cache/server/api/_hub/cache/batch-delete.post.ts
> fix(cache): handle cache keys with `.`

- src/features.ts
> fix(openapi): use direct import instead of nitro alias

- src/runtime/analytics/server/utils/analytics.ts
Fixing a typo: useAnalytics -> hubAnalytics
> chore: fix typo in analytics.ts

- docs/content/3.pricing.yml
Hi 👋🏻
Just submitting a small PR to correct the [included Cloudflare KV usage information](https://developers.cloudflare.com/kv/platform/pricing/) on the [pricing page](https://hub.nuxt.com/pricing).
> docs: update Cloudflare KV included usage information

- src/module.ts
This will avoid any side effects.
> fix: disable the usage of `nuxt generate`

- src/runtime/blob/server/utils/blob.ts
> fix(blob): handle Uint8Array format

- src/features.ts
> feat: support `nuxt-csurf` with zero-config

- src/runtime/blob/app/composables/useUpload.ts
- test/blob.test.ts
> fix(blob): handle FileList in useUpload

- docs/content/1.docs/2.features/kv.md
- docs/nuxt.config.ts
- docs/package.json
- package.json
- playground/app/pages/kv.vue
- playground/package.json
- playground/server/api/kv/index.get.ts
- playground/server/api/kv/index.put.ts
- pnpm-lock.yaml
- src/module.ts
- src/runtime/kv/server/utils/kv.ts
- src/types/kv.ts
We can now specify the ttl for expiring keys:
```ts
await hubKV('hello', 'stays-60-seconds', { ttl: 60 })
```
resolves #140
> feat(kv): add support for ttl

- src/runtime/ready.dev.ts
- test/fixtures/cache/server/api/cached.ts
> fix: use #imports for nitropack imports

- src/runtime/blob/app/composables/useUpload.ts
> fix: don't use global on client-side

- docs/content/1.docs/3.recipes/4.debug.md
> docs(recipes): fix typo

- docs/content/1.docs/2.features/blob.md
- playground/server/api/blob/get/[...pathname].get.ts
- src/runtime/blob/server/utils/blob.ts
It is now possible to fetch a Blob body with `.get()`:
```ts
const blob = await hubBlob().get(pathname)
```
> feat(blob): add `.get()`

- playground/server/api/browser/capture.ts
- src/runtime/blob/server/api/_hub/blob/[...pathname].put.ts
> fix(blob): respect `addRandomSuffix` with remote access

- src/features.ts
> feat: add noindex for preview env

- src/runtime/openai/server/tsconfig.json
- src/runtime/openapi/server/tsconfig.json
> fix: move tsconfig to correct folder

- src/module.ts
- src/utils/wrangler.ts
> chore: remove unused ai binding

- playground/app/pages/cached.vue
- playground/nuxt.config.ts
- src/features.ts
As CF bindings are not available, fallback to fs storage.
> fix: update cache storage for pre-rendering phase

- src/runtime/blob/server/api/_hub/blob/multipart/[action]/[...pathname].ts
- src/runtime/blob/server/utils/blob.ts
> fix: multipart with remote storage

- src/runtime/ai/server/utils/ai.ts
> fix: enable back AI in dev

- src/runtime/blob/server/utils/blob.ts
To handle special cases like `:` or ` ` with multipart upload (#314)
> fix(blob): encode pathname

- src/runtime/cache/server/api/_hub/cache/batch-delete.post.ts
- src/runtime/cache/server/api/_hub/cache/clear/[...base].delete.ts
Support batch delete using the CF API to remove the 1k limit
> feat(cache): support batch delete

- src/utils/build.ts
As the `compiled` hook from Nitro is the last one called.
> chore: use `compiled` hook from nitro to final build event

- src/runtime/vectorize/server/api/_hub/vectorize/[index]/[command].post.ts
> fix: make vectorize query params optional

- src/runtime/database/server/utils/migrations/remote.ts
> fix(migrations): respect for loop for remote db migrations

- docs/content/1.docs/3.recipes/4.debug.md
Simple typo fix in `debug.md`  💚
> docs: fix typo in debug

- docs/app/app.vue
> docs: fix header gradient shows above all the content (#483)

- package.json
> fix(types): add exports in package.json

- package.json
- playground/package.json
- pnpm-lock.yaml
- src/features.ts
- src/module.ts
- src/types/module.ts
Related https://github.com/nuxt-hub/cli/pull/61
> feat: environments
