docs/content/docs/1.getting-started/3.deploy.md
The getting started docs for Self-hosted Remote Storage instructs you to setup an environment variable named `NUXT_HUB_PROJECT_SECRET`. This, however, is incorrect. According to https://github.com/nuxt-hub/core/blob/main/src/module/index.ts it should be `NUXT_HUB_PROJECT_SECRET_KEY`.
=> Fixed env instructions for Self-hosted Remote Storage

README.md
This PR corrects the capitalisation of Cloudflare.
- https://blog.cloudflare.com/time-for-an-update
- https://developers.cloudflare.com/style-guide/grammar/parts-of-speech/capitalization/
I've noticed Cloud**F**lare mentioned in the GitHub descriptions too.
- https://github.com/nuxt-hub
- https://github.com/nuxt-hub/core
I apologise for taking up time with such a little PR.
=> fix: correct capitalisation for Cloudflare

docs/app.config.ts
The current config [base link](https://github.com/nuxt-hub/core/edit/main/content) points to `https://github.com/nuxt-hub/core/edit/main/content`, but the [correct base link](https://github.com/nuxt-hub/core/edit/main/docs/content) is `https://github.com/nuxt-hub/core/edit/main/docs/content`
=> fix: GitHub edit link for content in app.config.ts

docs/content/docs/3.recipes/2.drizzle.md
I followed through the Drizzle recipe in the docs and it seemed like the database migration did not go through with the following error:
```
[nitro] [unhandledRejection] Error: D1_ERROR: A prepared SQL statement must contain only one statement.
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at <anonymous> (C:\Users\Atom\Documents\GitHub\careear\server\plugins\migrations.ts:24:1)
at getBindingsProxy (C:\Users\Atom\Documents\GitHub\careear\node_modules\@nuxthub\core\src\module\runtime\bindings.dev.ts:57:1) {
[cause]: Error: A prepared SQL statement must contain only one statement.
at D1Database._sendOrThrow (cloudflare-internal:d1-api:67:24)
at async D1PreparedStatement.run (cloudflare-internal:d1-api:172:29) {
[cause]: undefined
}
}
```
I'm not sure how this …
=> Fix D1_ERROR: A prepared SQL statement must contain only one statement.

src/runtime/server/api/_hub/database/query.options.ts
When accessing the Database via the DevTools it shows a CORs error. This is due to the fetch occurring from an external domain (https://admin.hub.nuxt.com).
Normally this would be handled but we are filtering the route for `post` which is bypassing the `options` request.
This does not seem to be an issue for the other devtool pages.
=> fix: DevTools Database CORs error

src/module.ts, src/runtime/server/utils/features.ts
=> fix(remote-storage): raise error if storage is not enabled in the deployment

src/module.ts, src/runtime/server/api/_hub/openapi.get.ts, src/runtime/templates/openapi.ts
=> fix: fallback to custom placeholder when openAPI is disabled

src/module.ts
found this issue in a CI type test - we need the server utils to be _known_ so Nitro can write types in `prepare` step...
=> fix: ensure types for server utils are written in prepare step

docs/content/docs/1.getting-started/4.remote-storage.md, playground/nuxt.config.ts, src/module.ts
Update the `projectUrl` option to also be a function:
```ts
projectUrl?: string | (({ env, branch }: { env: 'production' | 'preview', branch: string }) => string)
```
This can be useful when wanting to specify the preview url for a specific branch:
```ts
projectUrl: ({ branch }) => branch === 'main' ? 'https://hello.nuxt.dev' : `https://dev.hello.nuxt.dev`
```
=> feat: support dynamic project url

src/runtime/server/api/_hub/database/[command].post.ts
Implemented better zod code to avoid duplication of validation.
Also, with this change the field `params` will be empty array by default, so users will be able to do something like:
```
/api/_hub/database/all 
body: { "query": "SELECT * FROM users" }
```
It was an error. `Invalid type for params`
=> chore: clean zod validation in database api endpoints

docs/content/docs/4.recipes/2.drizzle.md
Add a section to let users know how to populate their database using Nitro Tasks.
It would be great if we had an extensible component, something like
```md
::expandable{title="Click here to see details"}
Instructions...
::
```
Currently the seed config steps are quite long and not that useful for everyone, so it is a bit of a waste of space. I tried to create a component with `UAccordion` but was unsuccessful in getting it to work.
If you have a reference of somewhere with the same component I am happy to port it here or feel free to implement it yourself in this PR. Let me know what you think :)
=> docs: Add seed configuration for database population with Nitro Tasks

docs/content/docs/2.storage/3.blob.md, package.json, playground/pages/blob.vue, playground/server/api/blob/index.get.ts, playground/server/api/blob/index.put.ts, src/runtime/server/api/_hub/blob/index.get.ts, src/runtime/server/utils/blob.ts
resolves nuxt-hub/core#101
This creates a slightly breaking change when delimiter is defined in request
https://github.com/nuxt-hub/core/assets/2047945/ee7627f4-0972-4179-b064-8a76a80ea04a
=> !feat: simulate directory in blob list

docs/content/1.docs/2.storage/3.blob.md, playground/server/api/blob/index.put.ts, src/module.ts, src/runtime/compsables/useUpload.ts, src/runtime/cors.dev.ts, src/runtime/server/api/_hub/blob/head/[...pathname].get.ts, src/runtime/server/api/_hub/blob/index.post.ts, src/runtime/server/utils/auth.ts, src/runtime/server/utils/blob.ts
- add catch all fallback route in dev to enable Cors for devtools (we also can create a middleware in dev for this)
- Change `formKey`'s default value to `files` to be consistent with all version and prevent default mismatch
=> fix: blobs & cors issue

src/runtime/server/utils/blob.ts
fix #142
Add etag when serving blob to save bandwidth and speed up loading.
The server sends the etag and the browser adds `if-not-match` when asking the blob.
=> feat: use etag in blob.serve

package.json, pnpm-lock.yaml, src/runtime/server/utils/blob.ts
Converting filename to a slug format is not necessary for uploading files to Cloudflare R2
=> fix(blob): remove slugify

package.json, pnpm-lock.yaml, src/runtime/blob/app/composables/useMultipartUpload.ts, src/runtime/blob/app/composables/useUpload.ts, src/runtime/blob/server/utils/blob.ts, src/runtime/database/server/utils/database.ts, src/runtime/kv/server/utils/kv.ts
resolves https://github.com/nuxt-hub/core/issues/166
closes https://github.com/nuxt-hub/core/pull/167
=> fix: import runtime types from `@nuxthub/core`

docs/utils/index.ts
The sidebar on the docs invites to the regular Nuxt Discord rather than the NuxtHub one.
I've used the same public invite link shown on the pricing docs (docs/content/3.pricing.yml). NuxtHub admin dash -> feedback uses a different invite to the same server.
=> docs: use nuxthub discord invite

docs/content/1.docs/1.getting-started/3.deploy.md
On the github actions workflow, the pnpm action is not providing the pnpm version which make the build failing.
=> docs: missing pnpm version on github actions template

.github/workflows/autofix.yml
Hey team, a while ago I published a fix for the issue nuxt-hub/core had with pkg.pr.new. 
And I wonder if there's anything I can do to get it back, would love to hear your thoughts.
=> chore: uncomment pkg.pr.new 

.vscode/settings.json
Hello 👋,
Since eslint is enabled and used to format the code, I think it's a good idea to disable the vscode prettier extension to avoid conflicts between the two formatters.
=> chore: disable prettier

src/runtime/cache/server/api/_hub/cache/[...key].delete.ts, src/runtime/cache/server/api/_hub/cache/[...key].get.ts, src/runtime/cache/server/api/_hub/cache/batch-delete.post.ts, src/runtime/cache/server/api/_hub/cache/clear/[...base].delete.ts, src/runtime/cache/server/api/_hub/cache/index.get.ts, test/cache.test.ts
=> fix(cache): don't force nitro prefix

src/module.ts
This will allow the usage of package depending on `cloudflare:sockets` for example (`postgres`)
This can be done later on in Nitro itself (waiting for the next major release first), I will be able to remove this based on a specific Nitro version.
=> fix: add support for `cloudflare:*` externals

playground/nuxt.config.ts, playground/server/api/crypto.ts, src/features.ts, src/types/module.ts
For advanced use cases.
```ts
export default defineNuxtConfig({
hub: {
bindings: {
compatibilityDate: '2024-09-06'
}
}
})
```
=> feat: add support for defining compatibility date & flags

src/features.ts
Related to https://community.cloudflare.com/t/removing-trailing-slash-on-static-websites/583429
=> feat: remove trailing slash for prerender routes

src/module.ts, src/types/module.ts
So we can give a seamless experience when upgrading to Nitro future versions.
=> chore: use nitro compatibility flags by default

docs/content/1.docs/3.recipes/5.postgres.md
Updating docs based on a reply from @RihanArfan on discord, pointing out that [Cloudflare does support `pg` now](https://developers.cloudflare.com/hyperdrive/configuration/connect-to-postgres/#supported-drivers).
=> docs: update `pg` note

docs/content/1.docs/2.features/blob.md, src/runtime/blob/server/utils/blob.ts, src/types/blob.ts
Expose `httpEtag` and `httpMetadata` from blob object.
=> feat(blob): expose more data

src/runtime/database/server/utils/migrations/migrations.ts
resolves #31 
As the query to fetch the migrations fails in development (where we fallback to `[]` for remote migrations)
=> fix(database): create migrations table in dev

src/utils/build.ts
resolves #344 
Also reported by @harlan-zw ❤️
=> fix: only apply migrations if database is enabled

src/runtime/vectorize/server/utils/vectorize.ts
Closes #345
Correctly resolves the Vectorize type after build by importing it from from `@nuxthub/core`'s exported type. Behaviour matches D1 type for hubDatabase() now.
=> fix: correctly resolve vectorize type

docs/content/0.index.yml
Typo on the [home page](https://hub.nuxt.com/)
=> docs: typo index page

package.json, playground/nuxt.config.ts, pnpm-lock.yaml, src/features.ts, src/module.ts, src/runtime/openapi/server/api/_hub/openapi.get.ts, src/runtime/openapi/server/templates/openapi.ts
Leverage the generated `openapi.json` instead, this also fix the new deployments using Nitro 2.10.
=> fix(openapi): use new Nitro 2.10 format

src/runtime/database/server/api/_hub/database/[command].post.ts, src/runtime/database/server/utils/database.ts, src/types/database.ts
Cloudflare D1 `db.dump()` is deprecated and only available to D1 alpha databases. https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/#await-dbdump
As it wasn't documented on NuxtHub's docs, and that it wasn't usable either (as all databases should be newer than D1 Alpha), I believe this is not a breaking change.
=> chore: remove deprecated D1 dump()

docs/content/1.docs/2.features/blob.md
Hi !
It looks like the "contentTypes" property is not expected on the `ensureBlob` type and should be replaced with "types".
Later in the line, "images/png" seems to be a typo for "image/png".
Huge thanks for nuxt hub, so much fun to use !!
=> docs: update blob.md to match the ensureBlob types

docs/content/1.docs/3.recipes/5.postgres.md
Made the hyperdrive binding example be the same as every other binding used in the module.
Only checking `process.env.POSTGRES` returns `null` in my project.
The new example works perfectly
=> docs: improve postgres hyperdrive binding example

src/runtime/database/server/utils/migrations/helpers.ts, test/migration.helpers.test.ts
Having one of the below queries
```sql
insert into table (content) values ('---\nkey: value\n---');
insert into table (content) values ('```\n/* this is comment */\n```');
insert into table (content) values ('hello; world');
```
breaks migration execution
So far I have found three breaking characters.
- `--` inline comment format: Removes everything after `--` (assumes it is a comment)
- `/* */` multi-line comments: Removed content between
- `;` query separator: Splits to invalids queries
I added some tests to check splitter behavior, We can improve tests if some known edge cases are missing.
=> fix(migration): invalid behavior while using `--` or `/* */` inside column string

src/features.ts
=> fix(api): disable cache and prerender on `/api/_hub/**`

playground/test/basic.test.ts, src/module.ts, src/utils/wrangler.ts
This will help when working with tests so NuxtHub will use another dataset, useful to avoid writing on the development database.
Options to enable the hub test env:
- `NUXT_HUB_ENV=test`
- `nuxi dev --hub-env test`
- Running the dev server within Vitest with:
```ts
// basic.test.ts
import { fileURLToPath } from 'node:url'
import { describe } from 'vitest'
import { setup, $fetch } from '@nuxt/test-utils/e2e'
describe('test env', async () => {
await setup({
rootDir: fileURLToPath(new URL('..', import.meta.url)),
dev: true
})
// ...
})
```
=> feat: add hub `test` env as well as supporting nuxt test option

playground/server/api/blob/get/[...pathname].get.ts, src/runtime/blob/server/utils/blob.ts
=> fix(blob): return null for get() with remote enabled

docs/content/docs/1.getting-started/3.deploy.md
This PR enhances our documentation on managing environment variables within GitHub workflows.
1. It clarifies where to locate these variables and secrets in GitHub repository settings, helping users verify NuxtHub’s synchronization.
2. For private repositories on free GitHub accounts or organizations, the documentation now explains that environment variables must be manually configured and provides clear instructions on where to do so.
3. An example workflow has also been updated to demonstrate the use of both a public variable and a secret for private variables.
=> docs: improve environment variables part

docs/content/docs/1.getting-started/3.deploy.md
This Pull Request resolves #475 
Here I added a detailed documentation how to setup nuxthub with gitlab-ci.
Following features are mentioned:
- deploy with gitlab-ci (obviously) 
- Monorepo support
- Auto Deploy (default on pushes to staging and main)
- Manual triggers (benefit is reduction of overall internet traffic and run on demand if change detection not triggering)
- Bun support
- Job caching
I do not know if the mono repo stuff is maybe to much. Since you mentioned it for Github Actions its fair to also mention the how-to for gitlab.
Please review my changes, give critics and check grammar (no native english speaker, but did use grammar tools)
---
---
---
=> docs(gitlab-ci): adding gitlab-ci documentation

src/runtime/blob/server/utils/blob.ts
Cloudflare multi-part upload does not return `httpMetadata` and `customMetadata` when the upload is complete. As we depend on `customMetadata` to find `contentType` of the file, this behavior leads to undefined `contentType`.
There are two solutions so far:
1. call `hubBlob().head(mpu.key)` in upload complete and re-fetch the information on file (adds one extra read operation on all uploads)
2. re-evaluate contentType using our `getContentType` if it's missing. This PR proposes this solution.
=> fix(mpu): missing content type on complete

src/runtime/blob/app/composables/useMultipartUpload.ts, src/runtime/blob/server/utils/blob.ts
Send the file type via HTTP headers and read it in the multi-part upload creation.
=> feat: send file mime to multi-part upload

playground/app/pages/ai.vue, playground/server/api/chat.post.ts, src/runtime/ai/server/api/_hub/ai/[command].post.ts, src/runtime/ai/server/utils/ai.ts
Adding support AI gateway in development will speed up and reduce cost 🚀
=> feat(ai): support AI gateway in development too

src/module.ts, src/types/module.ts, src/utils/build.ts
If `hub.workers: true`, the Nitro preset is`cloudflare_module` or `cloudflare_durable` if `nitro.experimental.websocket` is enabled.
=> feat: support hub.workers

docs/content/blog/1.beta.md, docs/content/changelog/server-cache.md, docs/content/docs/2.features/cache.md, docs/content/docs/2.features/vectorize.md, docs/content/docs/3.recipes/2.drizzle.md
This PR updates outdated Nitro documentation links from `nitro.unjs.io` to the new domain `nitro.build`
=> fix(docs): update nitro.unjs.io links to nitro.build

package.json, pnpm-lock.yaml, src/utils/devtools.ts
Launch and view Drizzle Studio via Nuxt DevTools
- Automatically generates `drizzle.config.ts` based on Nitro Database configuration if user `drizzle.config.ts` doesn't exist in root
- Launches via dlx if user `drizzle.config.ts` doesn't exist in root
Blocked by https://github.com/unjs/nypm/pull/218
=> feat: database viewer
